server:
  port: 8070

spring:
  application:
    name: player-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-football
    username: postgres
    password: admin
  jpa:
    hibernate.ddl-auto: create
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"